/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package presentation.ui.guii;

/**
 *
 * @author wende
 */
public class AlterarSenha extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(AlterarSenha.class.getName());

    /**
     * Creates new form AlterarSenha
     */
    public AlterarSenha() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        pnlAlterarSenha = new javax.swing.JPanel();
        txtDigiteSenha = new javax.swing.JTextField();
        txtNovaPalavraPasse = new javax.swing.JTextField();
        txtConfirmarPasse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAlterarPass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtDigiteSenha.addActionListener(this::txtDigiteSenhaActionPerformed);

        txtNovaPalavraPasse.addActionListener(this::txtNovaPalavraPasseActionPerformed);

        txtConfirmarPasse.addActionListener(this::txtConfirmarPasseActionPerformed);

        jLabel4.setText("DIGITE A SENHA ");

        jLabel5.setText("CONFIRMAR NOVA PALAVRAR- PASSE ");

        jLabel6.setText("NOVA PALAVRA - PASSE ");

        btnAlterarPass.setText("ALTERAR PALAVRA-PASSE ");
        btnAlterarPass.addActionListener(this::btnAlterarPassActionPerformed);

        javax.swing.GroupLayout pnlAlterarSenhaLayout = new javax.swing.GroupLayout(pnlAlterarSenha);
        pnlAlterarSenha.setLayout(pnlAlterarSenhaLayout);
        pnlAlterarSenhaLayout.setHorizontalGroup(
            pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDigiteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNovaPalavraPasse, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmarPasse, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 101, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlterarSenhaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAlterarPass)
                .addGap(123, 123, 123))
            .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                    .addGap(170, 170, 170)
                    .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6))
                    .addContainerGap(301, Short.MAX_VALUE)))
        );
        pnlAlterarSenhaLayout.setVerticalGroup(
            pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlterarSenhaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(txtDigiteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNovaPalavraPasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtConfirmarPasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(39, 39, 39)
                .addComponent(btnAlterarPass)
                .addContainerGap(93, Short.MAX_VALUE))
            .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jLabel4)
                    .addGap(27, 27, 27)
                    .addComponent(jLabel6)
                    .addContainerGap(239, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 621, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAlterarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 328, Short.MAX_VALUE)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addComponent(pnlAlterarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addContainerGap()))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtDigiteSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigiteSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigiteSenhaActionPerformed

    private void txtNovaPalavraPasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovaPalavraPasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovaPalavraPasseActionPerformed

    private void txtConfirmarPasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmarPasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmarPasseActionPerformed

    private void btnAlterarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPassActionPerformed
        // TODO add your handprivate void btnAlterarPassActionPerformed(java.awt.event.ActionEvent evt) {

        String senhaAtual     = txtDigiteSenha.getText();
        String novaSenha      = txtNovaPalavraPasse.getText();
        String confirmarSenha = txtConfirmarPasse.getText();

     if (senhaAtual.isEmpty() || novaSenha.isEmpty() || confirmarSenha.isEmpty()) {
    javax.swing.JOptionPane.showMessageDialog(this, "Preenche todos os campos!");
    return;
   }
     if (!novaSenha.equals(confirmarSenha)) {
    javax.swing.JOptionPane.showMessageDialog(this, "As senhas não coincidem!");
    return;
   }
     if (novaSenha.length() < 6) {
    javax.swing.JOptionPane.showMessageDialog(this, "Mínimo 6 caracteres!");
    return;
   }

    try {
    Servicoes.UtilizadorDAO dao = new Servicoes.UtilizadorDAO();
    GestaoAcademia.Utilizador u = GestaoAcademia.Sessao.getUtilizadorAtual();

    if (!u.getPassword().equals(senhaAtual)) {
        javax.swing.JOptionPane.showMessageDialog(this, "Senha atual incorreta!");
        return;
    }

    dao.alterarPassword(u.getId(), novaSenha);
    u.setPassword(novaSenha);
    u.setPrimeiroLogin(false);

    javax.swing.JOptionPane.showMessageDialog(this, "Senha alterada com sucesso!");

    if (GestaoAcademia.Sessao.eTreinador()) {
        new PainelTreinador().setVisible(true);
    } else {
        new PainelCliente().setVisible(true);
    }
    this.dispose();

} catch (java.sql.SQLException e) {
    javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
}

    }//GEN-LAST:event_btnAlterarPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new AlterarSenha().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarPass;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlAlterarSenha;
    private javax.swing.JTextField txtConfirmarPasse;
    private javax.swing.JTextField txtDigiteSenha;
    private javax.swing.JTextField txtNovaPalavraPasse;
    // End of variables declaration//GEN-END:variables
}
