
package presentation.ui.guii;

/**
 *
 * @author wende
 */
public class Login extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(Login.class.getName());

    /**
     * Creates new form Login
     */
    public Login() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        txtAdicionarRegistro = new javax.swing.JTextField();
        txtSenha = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnEntrar = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        pnlAlterarSenha = new javax.swing.JPanel();
        txtDigiteSenha = new javax.swing.JTextField();
        txtNovaPalavraPasse = new javax.swing.JTextField();
        txtConfirmarPasse = new javax.swing.JTextField();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        btnAlterarPass = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        txtAdicionarRegistro.addActionListener(this::txtAdicionarRegistroActionPerformed);

        txtSenha.addActionListener(this::txtSenhaActionPerformed);

        jLabel1.setText("Login");

        jLabel2.setText("Password ");

        btnEntrar.setText("ENTRAR ");
        btnEntrar.addActionListener(this::btnEntrarActionPerformed);

        jLabel3.setText("GESTÃO GINASIO ");

        txtDigiteSenha.addActionListener(this::txtDigiteSenhaActionPerformed);

        txtNovaPalavraPasse.addActionListener(this::txtNovaPalavraPasseActionPerformed);

        txtConfirmarPasse.addActionListener(this::txtConfirmarPasseActionPerformed);

        jLabel4.setText("DIGITE A SENHA ");

        jLabel5.setText("CONFIRMAR NOVA PALAVRAR- PASSE ");

        jLabel6.setText("NOVA PALAVRA - PASSE ");

        btnAlterarPass.setText("ALTERAR PALAVRA-PASSE ");
        btnAlterarPass.addActionListener(this::btnAlterarPassActionPerformed);

        javax.swing.GroupLayout pnlAlterarSenhaLayout = new javax.swing.GroupLayout(pnlAlterarSenha);
        pnlAlterarSenha.setLayout(pnlAlterarSenhaLayout);
        pnlAlterarSenhaLayout.setHorizontalGroup(
            pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnAlterarPass)
                .addGap(120, 120, 120))
            .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                .addGap(88, 88, 88)
                .addComponent(jLabel5)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtDigiteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtNovaPalavraPasse, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(txtConfirmarPasse, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(0, 0, Short.MAX_VALUE))
            .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                    .addGap(170, 170, 170)
                    .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(jLabel4)
                        .addComponent(jLabel6))
                    .addContainerGap(301, Short.MAX_VALUE)))
        );
        pnlAlterarSenhaLayout.setVerticalGroup(
            pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, pnlAlterarSenhaLayout.createSequentialGroup()
                .addGap(65, 65, 65)
                .addComponent(txtDigiteSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(txtNovaPalavraPasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel5)
                    .addComponent(txtConfirmarPasse, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 57, Short.MAX_VALUE)
                .addComponent(btnAlterarPass)
                .addGap(126, 126, 126))
            .addGroup(pnlAlterarSenhaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(pnlAlterarSenhaLayout.createSequentialGroup()
                    .addGap(67, 67, 67)
                    .addComponent(jLabel4)
                    .addGap(27, 27, 27)
                    .addComponent(jLabel6)
                    .addContainerGap(239, Short.MAX_VALUE)))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addContainerGap(267, Short.MAX_VALUE)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 201, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(179, 179, 179))
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(110, 110, 110)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(btnEntrar)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(jLabel1)
                                    .addComponent(jLabel2))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                    .addComponent(txtSenha, javax.swing.GroupLayout.DEFAULT_SIZE, 218, Short.MAX_VALUE)
                                    .addComponent(txtAdicionarRegistro))))
                        .addGap(41, 41, 41))
                    .addComponent(pnlAlterarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtAdicionarRegistro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel1))
                .addGap(18, 18, 18)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(txtSenha, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2))
                .addGap(51, 51, 51)
                .addComponent(btnEntrar)
                .addGap(36, 36, 36)
                .addComponent(pnlAlterarSenha, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        txtAdicionarRegistro.getAccessibleContext().setAccessibleName("txtLogin");
        jLabel1.getAccessibleContext().setAccessibleName("Password ");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void txtAdicionarRegistroActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtAdicionarRegistroActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtAdicionarRegistroActionPerformed

    private void txtSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtSenhaActionPerformed

    private void btnEntrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEntrarActionPerformed
                                         

    String login    = txtAdicionarRegistro.getText().trim();
    String password = txtSenha.getText().trim();

    // Validação básica dos campos
    if (login.isEmpty() || password.isEmpty()) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Preenche o login e a password!");
        return;
    }

    try {
        // Usa o DAO para autenticar — não faz SQL diretamente aqui
        Servicoes.UtilizadorDAO dao = new Servicoes.UtilizadorDAO();
        GestaoAcademia.Utilizador utilizador = dao.autenticar(login, password);

        if (utilizador == null) {
            javax.swing.JOptionPane.showMessageDialog(this,
                "Login ou password incorretos!");
            return;
        }

        // Guarda na Sessao para qualquer JFrame poder aceder
        //GestaoAcademia.Sessao.setUtilizadorAtual(utilizador);

        javax.swing.JOptionPane.showMessageDialog(this, 
            "Bem-vindo, " + utilizador.getNome() + "!");

        // Verifica se é primeiro login → obriga a alterar senha
        if (utilizador.isPrimeiroLogin()) {
            //new AlterarSenha(utilizador).setVisible(true);
        } else {
            // Abre o painel correto conforme o tipo
            if (GestaoAcademia.Sessao.eTreinador()) {
                new PainelTreinador().setVisible(true);
            } else {
                new PainelCliente().setVisible(true);
            }
        }

        this.dispose(); // fecha o Login

    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this,
            "Erro de ligação: " + e.getMessage());
    }}
    }//GEN-LAST:event_btnEntrarActionPerformed

    private void txtDigiteSenhaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtDigiteSenhaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtDigiteSenhaActionPerformed

    private void txtNovaPalavraPasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtNovaPalavraPasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtNovaPalavraPasseActionPerformed

    private void txtConfirmarPasseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtConfirmarPasseActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtConfirmarPasseActionPerformed

    private void btnAlterarPassActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlterarPassActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAlterarPassActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new Login().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlterarPass;
    private javax.swing.JButton btnEntrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JPanel pnlAlterarSenha;
    private javax.swing.JTextField txtAdicionarRegistro;
    private javax.swing.JTextField txtConfirmarPasse;
    private javax.swing.JTextField txtDigiteSenha;
    private javax.swing.JTextField txtNovaPalavraPasse;
    private javax.swing.JTextField txtSenha;
    // End of variables declaration//GEN-END:variables
}
