
package presentation.ui.guii;

/**
 *
 * @author wende
 */
public class PainelTreinador extends javax.swing.JFrame {
    
    private static final java.util.logging.Logger logger = java.util.logging.Logger.getLogger(PainelTreinador.class.getName());

    /**
     * Creates new form PainelTreinador
     */
    public PainelTreinador() {
        initComponents();
        carregarAulas();
        carregarClientes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnNovoClientes = new javax.swing.JButton();
        btnAdicionarAula = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        tblTodasAulas = new javax.swing.JTable();
        jScrollPane2 = new javax.swing.JScrollPane();
        tblClientesRegistrados = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        btnCancelar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnNovoClientes.setText("NOVO CLIENTE ");

        btnAdicionarAula.setText("ADICIONAR AULA");
        btnAdicionarAula.addActionListener(this::btnAdicionarAulaActionPerformed);

        tblTodasAulas.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Nome", "Data/Hora ", "Duração", "Vagas", "Inscritos  ", "Estado "
            }
        ));
        jScrollPane1.setViewportView(tblTodasAulas);
        if (tblTodasAulas.getColumnModel().getColumnCount() > 0) {
            tblTodasAulas.getColumnModel().getColumn(0).setHeaderValue("Nome");
            tblTodasAulas.getColumnModel().getColumn(1).setHeaderValue("Data/Hora ");
            tblTodasAulas.getColumnModel().getColumn(2).setHeaderValue("Duração");
        }

        tblClientesRegistrados.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null},
                {null, null, null, null}
            },
            new String [] {
                "Nome", "Email  ", "Telefone", "Inscrições "
            }
        ));
        jScrollPane2.setViewportView(tblClientesRegistrados);

        jLabel1.setText("CLIENTES REGISTRADOS");

        jLabel2.setText("TODAS AS AULAS");

        btnCancelar.setText("Cancelar");
        btnCancelar.addActionListener(this::btnCancelarActionPerformed);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                                .addGap(0, 0, Short.MAX_VALUE)
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 591, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addGap(43, 43, 43)
                                        .addComponent(jLabel1))
                                    .addComponent(jLabel2))
                                .addGap(0, 0, Short.MAX_VALUE)))
                        .addContainerGap())
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(btnNovoClientes)
                        .addGap(18, 18, 18)
                        .addComponent(btnAdicionarAula)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnCancelar)
                        .addGap(35, 35, 35))))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(55, 55, 55)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnNovoClientes)
                    .addComponent(btnAdicionarAula)
                    .addComponent(btnCancelar))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 230, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 205, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(31, 31, 31))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnCancelarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCancelarActionPerformed
        new Login().setVisible(true);
        this.dispose();
    }//GEN-LAST:event_btnCancelarActionPerformed

    private void btnAdicionarAulaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAdicionarAulaActionPerformed
        new AdicionarAula().setVisible(true);
    }//GEN-LAST:event_btnAdicionarAulaActionPerformed
private void carregarClientes() {
    try {
        java.sql.Connection con = conexao.Conexao.getConexao();

        // Parâmetro: query SQL com LEFT JOIN e COUNT
        // Âmbito: método privado — só acessível dentro de PainelTreinador (encapsulamento)
        java.sql.ResultSet rs = con.createStatement().executeQuery(
            "SELECT c.nome, c.email, c.telefone, COUNT(i.id) AS inscricoes " +
            "FROM cliente c " +
            "LEFT JOIN inscricao i ON c.id = i.cliente_id " +
            "GROUP BY c.id, c.nome, c.email, c.telefone");

        // DefaultTableModel — objeto que serve de modelo de dados para a JTable
        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
            new String[]{"Nome", "Email", "Telefone", "Inscrições"}, 0);

        // Iteração sobre o ResultSet — cada linha da BD torna-se uma linha na tabela
        while (rs.next()) {
            modelo.addRow(new Object[]{
                rs.getString("nome"),
                rs.getString("email"),
                rs.getString("telefone"),
                rs.getInt("inscricoes")
            });
        }
        /*
         Encapsulamento - tblClientesRegistrados é privado, só alterado por este método
        */
        
        tblClientesRegistrados.setModel(modelo);

    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
      }
   }
    private void carregarAulas() {
    try {
        java.sql.Connection con = conexao.Conexao.getConexao();
        java.sql.ResultSet rs = con.createStatement().executeQuery(
            "SELECT a.nome, a.data_hora_inicio, a.duracao, a.capacidade, " +
            "COUNT(i.id) AS inscritos " +
            "FROM aula a " +
            "LEFT JOIN inscricao i ON a.id = i.aula_id " +
            "GROUP BY a.id, a.nome, a.data_hora_inicio, a.duracao, a.capacidade");

        javax.swing.table.DefaultTableModel modelo = new javax.swing.table.DefaultTableModel(
            new String[]{"Nome", "Data/Hora", "Duração", "Vagas", "Inscritos", "Estado"}, 0);

        while (rs.next()) {
            int vagas     = rs.getInt("capacidade");
            int inscritos = rs.getInt("inscritos");
            String estado;

            if (inscritos >= vagas) {
                estado = "Lotada";
            } else {
                estado = "Disponivel";
            }

            modelo.addRow(new Object[]{
                rs.getString("nome"),
                rs.getString("data_hora_inicio"),
                rs.getInt("duracao"),
                vagas,
                inscritos,
                estado
            });
        }

        tblTodasAulas.setModel(modelo);

    } catch (java.sql.SQLException e) {
        javax.swing.JOptionPane.showMessageDialog(this, "Erro: " + e.getMessage());
    }
}
   
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ReflectiveOperationException | javax.swing.UnsupportedLookAndFeelException ex) {
            logger.log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> new PainelTreinador().setVisible(true));
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAdicionarAula;
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnNovoClientes;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTable tblClientesRegistrados;
    private javax.swing.JTable tblTodasAulas;
    // End of variables declaration//GEN-END:variables
}
